server:
  port: 8080

spring:
  # MySQL
  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis
  redis:
    cache:
      port: 6379
    session:
      port: 6379
  
  # DB 접속 정보 숨기기
  profiles:
    include: secret

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ghm.giftcardfleamarket.domain.*.domain, com.ghm.giftcardfleamarket.domain.*.model