spring:
  profiles:
    active: dev # 활성화할 profile

---
# development
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL  # mem : 디스크가 아닌 메모리에 저장되는 In-memory 모드
    driverClassName: org.h2.Driver
    username: sa
    password:

---
# production
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flea_market
    username: root
    password: 1234
