name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      parameter:
        description: 'Parameter'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        run: |
          cd app/flea-market/gift-card-flea-market
          touch ./src/main/resources/application-secret.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-secret.yml
          cat ./src/main/resources/application-secret.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Deploy to Naver Cloud Platform
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          port: ${{ secrets.NCP_SERVER_SSH_PORT }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          script: |
            cd app/flea-market
            chmod +x ./deploy.sh
            ./deploy.sh ${{ github.event.inputs.parameter }}